checks:
    file-lines:
        config:
            threshold: 500
    method-count:
        config:
            threshold: 30
    method-lines:
        config:
            threshold: 75
engines:
    eslint:
        enabled: true
    csslint:
        enabled: true
        checks:
            box-sizing:
                enabled: false
    duplication:
        enabled: true
        config:
            languages:
            - javascript:
ratings:
    paths:
    - "src/**"
    - "**.js"
